iterations:
  naive:
    data: test
    processor: basic
    prompt: naive
    models: 
      - meta/llama-3.3-70b-instruct
      - mistralai/mixtral-8x22b-instruct-v0.1
      - google/gemma-2-9b-it
      - microsoft/phi-3-small-128k-instruct
      - microsoft/phi-4-mini-instruct
    temperature: 0.1
    top_p: 0.9
    max_tokens: 8192
